### PR TITLE
Some setup and add info and current plans to README.

### PR DESCRIPTION
**Pull request by VictorGrayDallas**
I have placed one question in the README: Should we install a SQL server, or can we use SQLite (which Djando projects use by default)?
Feel free to suggest any changes, or bring up anything that is missing or incorrect.

### CODE REVIEW

**Comment by swordgeo** [comment]
If I recall SQLite has limited concurrency since it locks the entire database during writing. Seeing as (in theory) we'd have a ton of users constantly doing things, this may not work well for us. MySQL or better yet SQL Server would serve us better I think.

**Comment by ThobiWanKenobi** [comment]
Well, but you also have to remember we are "just" creating an MVP, there is a limit to how hard you need to make it on yourself, there is very limited time to develop, and if you have to spend much of that time, just setting up a SQL server, and getting everyone on the idea, that will just be a lot of wasted time :)

At least, just be careful about the decision, as it is sad if you waste too much time on it.

**Comment by VictorGrayDallas** [comment]
I just added a sample page using Django and React (through Vite) and I think I'm happy with this.

**Comment by ThobiWanKenobi** [comment]
I just skimmed over the setup, and it looks pretty solid :) Seems quite simple, and it looks like this is more optimized to mix the technologies!

**Review by swordgeo — APPROVED** [review]
If it looks good to Thobias it looks good to me

**Pull request merged**
