### PR TITLE
created react frontend folder and django backend folder

### PR DESCRIPTION
**Pull request by swordgeo**
Made the skeletons for React frontend/Django backend folders by running the following:

python -m venv venv
venv\Scripts\activate

make backend folder

inside venv, inside backend folder:

pip install django
django-admin startproject myproject .

cd ..
mkdir frontend
cd frontend
npx create-react-app myapp

### CODE REVIEW

**Comment by VictorGrayDallas** [comment]
I've been looking at React a bit, and right now I don't think that create-ract-app is what we want. For one, it isn't being maintained anymore (and does have significant issues), ~~and two it looks like it's tied to next.js~~ and I don't think we want a React framework like that since we'll be using Django.
I don't know what we do want, but I'll be looking into that more today.

**Comment by swordgeo** [comment]
Fair enough. I was going the direction ChatGPT recommended because I certainly don't know any better.

**Comment by ThobiWanKenobi** [comment]
I am sorry to say, but chatGPT is not a savior in programming, in fact, you have to work with something REALLY simple to get anything close to correct or meaningful from it. Sometimes, it can cause more trouble, than anything :/

**Comment by swordgeo** [comment]
You're absolutely right about that. Since I know nothing of React and Django I figured it could help me learn a bit how to get started. I'm glad you guys are here to catch me from doing something we'll find to be inconvenient later on.

**Comment by ThobiWanKenobi** [comment]
From speaking to Victor yesterday, I think we should head in the direction of using Vite, I only have slight experience with it, but it is true they do have direct integration with Django, which I think is more optimal, and well, as it should be :) I will be doing a test of it soon and soon how it runs

**Comment by swordgeo** [comment]
Sounds good to me. I fork what he's got so I can start working in that direction

**Pull request closed without merging**
