### PR TITLE
Set up pages for patient reports feature

### PR DESCRIPTION
**Pull request by lmekeel**
Changes made:

-I updated the models to have needed properties
-Added pages for PatientList, PatientReportsShort (To Be Renamed), and AddReport
-Finished CSS styling for the patientList page
-Added an image asset for the calender/schedule for styling the page
-Removed my old HTML templates
-Removed my old views

### CODE REVIEW

**Comment by VictorGrayDallas** [comment]
The test data scripts don't work, because you have empty lines inside functions. (E.g., line 29 in TestDataSetup.py) This causes the interactive Python shell to think the function has ended, so the next line is an unexpected indentation.
Even if you had spaces there at some point to make it work, it's possible VS Code automatically removed them. Adding a comment on those lines (even just a # character) will prevent this.

You also should not have `if __name__ == "__main__":` in the script.

**Comment by VictorGrayDallas** [comment]
Also please turn off auto-formatting in your editor, so future commits are cleaner. There are a bunch of changes in this commit that are just auto-formatting, which makes it more difficult to see the actual changes.

**Comment by lmekeel** [comment]
- I cleaned up the comments and print statements
-Removed @csrf_exempt. I believe that was a tutorial or ChatGPT thing recommended on forms. 
-I added in the prop for hiding parts of the Patient List component. 
-Fixed spacing in TestDataSetup and Cleanup.

**Comment by VictorGrayDallas** [comment]
The test data scripts still weren't quite right. I realized we can mostly avoid these problems by putting the existing functions in a new file, which are then imported from the setup file that gets run with `python manage.py shell < file.py`. I committed this change for both our app's test data scripts, putting them both in the new test_data directory and making it easy to run both at once.

**Review by VictorGrayDallas — APPROVED** [review]

**Pull request merged**
