### PR TITLE
Created venv and re-installed django and django_vite

### PR DESCRIPTION
**Pull request by swordgeo**

### CODE REVIEW

**Comment by swordgeo** [comment]
inside of scrub_hub_project, I ran
python -m venv venv

This created the virtual environment.
Inside the same directory, to activate the venv before every session we use
venv\Scripts\activate

Now I was able to pip install django and django_vite
Then navigated to sub_hub_vite
npm install
npm run dev

So from now on, as the README reflects, we will
    In first terminal:
* From scrub_hub_project: venv\Scripts\activate
* From scrub_hub_project: python manage.py runserver

    In second terminal
* From scrub_hub_project: venv\Scripts\activate
* From scrub_hub_vite: npm run dev

We should never have to force each other to npm or pip install anything again.
If we install a new dependency inside the venv, and merge the change, we will now all have access to those newer dependencies

**Comment by VictorGrayDallas** [comment]
Just a quick look, shouldn't venv/Lib/site-packages be in the .gitignore and not be committed?

**Comment by swordgeo** [comment]
You are right, my mistake. I added a requirements.txt file which should make us happy at this point

**Comment by VictorGrayDallas** [comment]
I pulled the branch to test it out, and I found there are a couple of extra steps not mentioned in your README update.
First, each person must create their own virtual environment on their own computer: `python -m venv venv`
Second, after running the activate script they have to install the dependencies from requirements.txt: `pip install -r requirements.txt`

**Pull request closed without merging**
